n0-computer/quic-rpc

examples/macro.rs
src/lib.rs
src/macros.rs
src/server.rs

Copied from https://github.com/n0-computer/quic-rpc/pull/1 :
I digged out some macro_rules code for RPC interface declarations that I wrote for an RPC experiment a while back. It was quite straightforward to adapt to quic-rpc, combined it with the request_enum macro from examples/store.rs and then got lost a bit and made the store example work.
The macros are completely optional. They also do not introduce any traits, because async traits would require boxing the futures, and so far quic-rpc works without, which is nice.
All idents have to be passed in the macro call. I think that's a feature because less magic. The invocation of derive_rpc_service! in examples/macro.rs quite literally creates the code that can be seen in examples/store.rs.

feat: add optional macros to reduce boilerplate

---

Cargo.lock
Cargo.toml
examples/macro.rs
examples/split/client/Cargo.toml
examples/split/client/src/main.rs
examples/split/server/Cargo.toml
examples/split/server/src/main.rs
examples/split/types/Cargo.toml
examples/split/types/src/lib.rs
src/macros.rs
src/server.rs

It is often useful to have the RPC types in a seperate crate, so that a client-only usage does not have to import the server implemenation.
This makes this possible while keeping the macros to reduce boilerplate.
The generation of the dispatch function is made optional, and moved into a *generated macro*. This allows to only create the dispatch function in the *server* part, while the *client* part only uses the generated types.
The macro example is updated accordingly. A new *split* example demonstrates the full client-server usage flow over quic.

feat: improve macro for splitting crates and generate client

---

src/transport/http2.rs
tests/http2.rs

This will terminate the hyper server when the ServerChannel is
dropped.  Previously it kept running in a task.
Closes #14

feat(http2): Shut down the hyper server on drop.

---

src/transport/http2.rs

For now only allow max frame size to be configurable. There will be more.
Also set the default to the highest possible value. The rationale being that it is preferable to waste a bit of memory by default over things not working.
tcp nodelay is not in the config because it is not relevant for all channels, just tcp channels.

feature: make channels configurable

---

examples/split/server/src/main.rs
src/lib.rs
src/server.rs
src/transport/combined.rs
src/transport/http2.rs
src/transport/mem.rs
src/transport/quinn.rs
tests/quinn.rs

This adds the ability to expose the local address the ServerChannel is bound to.  This allows binding to wildcard ports and still knowing which address is used.

feat: Expose local address of ServerChannel

---

src/transport/http2.rs

avoid a copy for the very common case that 1 arriving chunk = 1 frame, by trying to deserialize directly from the arriving Bytes buffer.
Implements https://github.com/n0-computer/quic-rpc/issues/27

perf: avoid copying data when receiving full frames

---

examples/errors.rs
examples/macro.rs
examples/split/client/src/main.rs
examples/split/server/src/main.rs
examples/store.rs
src/lib.rs
src/server.rs
src/transport/combined.rs
src/transport/http2.rs
src/transport/mem.rs
src/transport/mod.rs
src/transport/quinn.rs
tests/http2.rs
tests/mem.rs
tests/quinn.rs

This is certainly opinionated, and I will only be a little sad if we
don't decide to do this.  It changes the names of the ServerChannel
and ClientChannel to include the type.  Crucially the types now have
different names than the traits they implement.
This was already done at the
transport mod.rs for ChannelTypes, kind of showing this is generally
not bad.  It is also how I've seen most Rust code.
It is a bit more verbose for writing, but this does help (me) a lot
while reading the code, which is what counts.

ref: Rename main structs not conflict with trait names

---

Cargo.lock
Cargo.toml
src/transport/quinn.rs

It seems that if the client end of a quinn connection is just dropped, the server will keep its end around until a timeout.
this should fix it.

fix: explicitly close channel when client is dropped

---

Cargo.toml
examples/store.rs
tests/hyper.rs

Fixes `non_local_definitions` in nightly.
Note that this is not a clippy error but a compiler error.
I don't actually understand the complain from the compiler. Minimal examples creating an enumeration and adding a simple Display impl inside a test do not trigger the error. I wouldn't look _too much_ into it while false positives are being reported and fixed. That being said, moving the definitions and implementations outside the test fixes the issues
Also upgrade the minimal versions of anyhow and serde, as both fail in nightly

fix: nightly failures

---

Cargo.toml
examples/modularize.rs
src/client.rs
src/lib.rs
src/map.rs
src/server.rs
tests/flume.rs
tests/math.rs
tests/quinn.rs

It was quite a ride through the generics in this crate, but I finally found a solution for how to nicely decouple RPC services between modules or crates.
Importantly, it allows for an outer, app-level RPC service to delegate to inner services which are defined in other modules or crates. The inner services are regular quic-rpc services, and can even run on their own without the outer service. They take a single additional generic, so the code does not become horribly more generic.
See the [`modularize` example](https://github.com/n0-computer/quic-rpc/pull/67/files#diff-1e2caabb88ad7edadc4021df91911d45d413d0fbb10c8bd16684a4c88d55f82e) for a full, end-to-end example that composes RPC services from two different modules (which could be crates as well).
*Edit* I found a new approach that …

feat: Allow to compose RPC services

---

Cargo.toml
tests/hyper.rs

This enables all features for doc.rs builds, this should make sure all
the optional features are documented.
Fixes #59

chore(docs): enable all features for docs.rs builds

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
examples/split/types/Cargo.toml
src/client.rs
src/lib.rs
src/message.rs
src/pattern/bidi_streaming.rs
src/pattern/client_streaming.rs
src/pattern/mod.rs
src/pattern/rpc.rs
src/pattern/server_streaming.rs
src/pattern/try_server_streaming.rs
src/server.rs
tests/hyper.rs
tests/try.rs

also reorganize this into a separate pattern dir.
I think we need to separate out the patterns more. E.g. in some cases it would be useful if you don't have a fn that returns a stream but get a fn that gets a sink.
In any case, this is the attempt to do an interaction pattern that is more friendly to the case where the stream creation itself is async and fallible, and the stream contains results.
For usage, see the example in the try.rs test.

Add TryServerStreaming interaction pattern

---

Cargo.lock
Cargo.toml

We need a new version number according to semver-checks:
```
❯ cargo semver-checks
Parsing quic-rpc v0.7.0 (current)
Parsed [  22.468s] (current)
Parsing quic-rpc v0.7.0 (baseline)
Parsed [  22.495s] (baseline)
Checking quic-rpc v0.7.0 -> v0.7.0 (no change)
Checked [   0.023s] 67 checks; 66 passed, 1 failed, 0 unnecessary
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.30.0/src/lints/enum_missing.ron
Failed in:
enum quic_rpc::client::ClientStreamingItemError, previously in file …
```

increase version number

---

Cargo.lock
Cargo.toml
examples/split/client/Cargo.toml
examples/split/server/Cargo.toml
src/pattern/bidi_streaming.rs
src/pattern/client_streaming.rs
src/pattern/rpc.rs
src/pattern/server_streaming.rs
src/pattern/try_server_streaming.rs

Iroh itself is changing it's dependency to iroh-quinn, change it here as well.
This prepares the release as well by bumping the version number.

deps: Depend on iroh-quinn and bump version

---

src/transport/combined.rs
src/transport/flume.rs
src/transport/hyper.rs
src/transport/misc/mod.rs
src/transport/mod.rs
src/transport/quinn.rs

this allows us to get rid of lots of manual futures impls

Use return position impl trait in trait

---

Cargo.toml
src/transport/boxed.rs
src/transport/flume.rs
src/transport/mod.rs

Boxed transform that allows to unify different transports without having to have a type parameter.
It has a special case for the memory transport so that one is not boxing.

Add boxed transport

---

src/transport/boxed.rs

otherwise it is not possible to implemeent Boxable... traits

Make the boxed constructor public for both futures

---

examples/store.rs
src/pattern/bidi_streaming.rs
src/pattern/client_streaming.rs
src/pattern/rpc.rs
src/pattern/server_streaming.rs
src/pattern/try_server_streaming.rs
src/server.rs
src/transport/boxed.rs
src/transport/combined.rs
src/transport/flume.rs
src/transport/hyper.rs
src/transport/misc/mod.rs
src/transport/mod.rs
src/transport/quinn.rs

We only support bidirectional, so no need to disambiguate...

Rename open_bi and accept_bi to just open and accept

---

Cargo.lock
Cargo.toml
quic-rpc-derive/Cargo.toml
quic-rpc-derive/src/lib.rs
quic-rpc-derive/tests/compile_fail/duplicate_type.rs
quic-rpc-derive/tests/compile_fail/duplicate_type.stderr
quic-rpc-derive/tests/compile_fail/extra_attr_types.rs
quic-rpc-derive/tests/compile_fail/extra_attr_types.stderr
quic-rpc-derive/tests/compile_fail/multiple_fields.rs
quic-rpc-derive/tests/compile_fail/multiple_fields.stderr
quic-rpc-derive/tests/compile_fail/named_enum.rs
quic-rpc-derive/tests/compile_fail/named_enum.stderr
quic-rpc-derive/tests/compile_fail/non_enum.rs
quic-rpc-derive/tests/compile_fail/non_enum.stderr
quic-rpc-derive/tests/compile_fail/wrong_attr_types.rs
quic-rpc-derive/tests/compile_fail/wrong_attr_types.stderr
quic-rpc-derive/tests/smoke.rs

The way the interaction patterns are specified is very flexible and does a very good job explaining it to the compiler.
However, a downside is that it is pretty verbose and that you don't have a single place to grasp how a service works.
This PR adds an additional macro crate that allows annotating the request enum with the interaction pattern for each request type. It does not require any changes to quic-rpc itself, just basically derives the various quic-rpc message traits.
Example syntax:
```rust
#[rpc_requests(Service)]
#[derive(Debug, Serialize, Deserialize, derive_more::From, derive_more::TryInto)]
enum Request {
#[rpc(response=u32)]
Rpc(RpcRequest),
#[server_streaming(response=())]
ServerStreaming(ServerStreamingRequest),
#[bidi_streaming(update=(), response = ())] …
```

Add macro crate to allow placing rpc interation patterns directly on the request enum.

---

Cargo.lock
Cargo.toml
tests/quinn.rs

Quinn now re-exports the correct version of rustls that should be used with it.  Let's depend on that instead of having to manually keep the dependency in sync.

deps: Remove direct rustls dependency

---

Cargo.lock
Cargo.toml
examples/errors.rs
examples/macro.rs
examples/modularize.rs
examples/split/client/src/main.rs
examples/split/server/src/main.rs
examples/store.rs
quic-rpc-derive/Cargo.toml
src/client.rs
src/lib.rs
src/macros.rs
src/pattern/bidi_streaming.rs
src/pattern/client_streaming.rs
src/pattern/rpc.rs
src/pattern/server_streaming.rs
src/pattern/try_server_streaming.rs
src/server.rs
src/transport/boxed.rs
src/transport/combined.rs
src/transport/flume.rs
src/transport/hyper.rs
src/transport/mod.rs
src/transport/quinn.rs
tests/flume.rs
tests/hyper.rs
tests/math.rs
tests/quinn.rs
tests/try.rs

This moves the service type parameter that determines what rpc methods will actually be available on a RpcClient or RpcChannel, to the front.
For users that don't use modular services, this does not make a difference. For users that do, this makes it easier to specify the most more important visible service type.
It also disentangles the concept of services from the transport module. Ideally the transport module should be thought of as its own crate without any knowledge of the Service trait.

Composable service refactor

---

.rustfmt.toml

Based on https://github.com/n0-computer/quic-rpc/pull/113 with some other tweaks. All files already formatted, just introducing this config file so we have a more normalized formatting.

chore: introduce a .rustfmt.toml file with configs for  automatic formatting

---

Cargo.toml
examples/modularize.rs
src/server.rs
tests/flume.rs
tests/hyper.rs
tests/iroh-net.rs
tests/math.rs
tests/quinn.rs

This adds a fn to RpcServer to run an accept loop, as well as a fn that spawns an accept loop.
This is to DRY the various places where we now have accept loops, such as
https://github.com/n0-computer/iroh-blobs/pull/11
https://github.com/n0-computer/iroh-docs/pull/7
https://github.com/n0-computer/iroh-gossip/pull/7
This also allows making the tests a bit shorter - you don't have to call abort explicitly anymore on the server JoinHandle.

feat: Accept handler

---

Cargo.lock
Cargo.toml
examples/split/client/Cargo.toml
examples/split/server/Cargo.toml
examples/split/types/Cargo.toml

@rklaehn Should we work to bump hyper to 1.5?

chore: prune some deps

---

Cargo.lock
Cargo.toml

This is not necessary anymore. `cc` version 1.2 was released and fixes the issues that versions 1.32-1.37 had.

chore: Remove `cc` version pinning

---

Cargo.lock
Cargo.toml
src/transport/boxed.rs
src/transport/hyper.rs
src/transport/iroh_net.rs
src/transport/mod.rs
src/transport/quinn.rs
src/transport/util.rs
tests/hyper.rs

Implements https://github.com/n0-computer/quic-rpc/issues/108
Not sure about this. I like postcard because of the simplicity, but there is a slight perf decrease:
quinn transport:
main:
RPC seq 24_188 rps                                                              
RPC par 204_800 rps                                                             
bidi seq 303_453 rps 
this branch:
RPC seq 23_582 rps                                                              
RPC par 198_579 rps                                                             
bidi seq 254_606 rps
hyper transport:
main:
RPC seq 16_149 rps
RPC par 73_340 rps
bidi seq 535_791 rps
this branch:
RPC seq 15_223 rps
RPC par 73_061 rps
bidi seq 531_071 rps
Probably not worth obsessing about though. Pretty sure byte arrays will perform …

feat: use postcard encoding for all transports that require serialization

---

Cargo.toml

the bytes dependency was missing for the quinn transport. Having this dependency optional is a bit silly since if you use tokio in 99% of all cases you have it anyway. But still, this fixes it.
This was not caught by cargo test --all-features because the hyper feature does add it. I think it was introduced by the switch to postcard.

fix: add back bytes dependency for quinn transport

---

Cargo.lock
Cargo.toml
quic-rpc-derive/Cargo.toml

Release v0.17.1
- bugfix for the quinn-transport: the bytes dependency was missing

chore: release v0.17.1

---

Cargo.lock
Cargo.toml
DOCS.md
README.md
examples/split/server/Cargo.toml
examples/split/server/src/main.rs
src/lib.rs
src/transport/mod.rs

no luck so far...
Building docs locally using this command line:
```
RUSTFLAGS="--cfg iroh_docsrs" cargo +nightly doc --all-features --no-deps
```
Yet the feature flag blobs are nowhere to be seen.
I am about to give up and just manually put a "Needs `flume-transport` feature flag." in the docs.

Try to get feature flags in docs to work

---

Cargo.lock
Cargo.toml
DOCS.md
README.md
examples/split/client/Cargo.toml
examples/split/client/src/main.rs
examples/split/server/Cargo.toml
examples/split/server/src/main.rs
examples/split/types/Cargo.toml
quic-rpc-derive/Cargo.toml
src/client.rs
src/lib.rs
src/server.rs
src/transport/mod.rs
src/transport/quinn.rs
tests/quinn.rs

Copying and updating these gets really old.
This also fixes a bug in the fn make_insecure_client_endpoint that would not support any verification schemes, causing the split example to fail.
We also add some top level type aliases and fns for creating channels for mem and testing.
We get a dependency on rcgen and rustls, but only if you set the "test-utils" feature flag. Everybody that wants to use the quinn transport is going to want such tests in their crate, and this way we can do the whole setup only once.

Add connection setup helpers to the quinn transport.

---

Cargo.lock
Cargo.toml

chore: release 0.17.2
also remove bincode dependency that somehow got overlooked during the switch to postcard.

chore: release 0.17.2

---

Cargo.lock
Cargo.toml
src/transport/boxed.rs

Note: we've been ignoring the "minimal crates" failure in our releases: https://github.com/n0-computer/quic-rpc/issues/110

chore: upgrade to `iroh@v0.33

---

src/server.rs

It seems that under some weird circumstances we get a situation where an oneshot channel is polled after completion. Oneshot channel is not fused for no good reason that I can see, so we get a panic.
This did not happen before, but now it happens more frequently and causes frequent test failures in iroh-blobs CI.
There is a way to detect an already terminated oneshot channel in tokio 1.44 from 2025-03-07, so we could just modify the poll fn of the wrapper to call that. But since I don't want to update the tokio dep for a patch, I just wrap it in a fuse. We can do the is_terminated thing once we get tokio 1.44.

fix: Fuse oneshot channel
